"""Sync models

Revision ID: d7dc54106316
Revises: 0001
Create Date: 2026-02-28 19:40:29.464149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7dc54106316'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_logs', 'routing_decision',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Routing engine decision details (provider, reason, fallback info)',
               existing_comment='Routing engine decision details',
               existing_nullable=True)
    op.drop_constraint(op.f('request_logs_request_id_key'), 'request_logs', type_='unique')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=False)
    op.create_unique_constraint(op.f('request_logs_request_id_key'), 'request_logs', ['request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('request_logs', 'routing_decision',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Routing engine decision details',
               existing_comment='Routing engine decision details (provider, reason, fallback info)',
               existing_nullable=True)
    # ### end Alembic commands ###
