apiVersion: v1
kind: Service
metadata:
  name: ftgo-order-history-service
  namespace: ftgo
  labels:
    app: order-history-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: order-history-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-order-history-service-config
  namespace: ftgo
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ftgo-postgres-postgresql:5432/postgres"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
---
apiVersion: v1
kind: Secret
metadata:
  name: ftgo-order-history-service-secret
  namespace: ftgo
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
