apiVersion: v1
kind: Secret
metadata:
  name: ftgo-accounting-service-secret
  namespace: ftgo
  labels:
    app: ftgo-accounting-service
    component: accounting
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  SPRING_DATASOURCE_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
