apiVersion: v1
kind: Secret
metadata:
  name: universal-ai-gateway-secret
  namespace: ftgo
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  JWT_SECRET_KEY: c3VwZXJzZWNyZXRqd3RrZXlmb3JmdGdvYXBpZ2F0ZXdheTFyYW5kb20=
