apiVersion: v1
kind: Secret
metadata:
  name: universal-ai-gateway-secret
  namespace: ftgo
type: Opaque
data:
  DATABASE_URL: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  REDIS_URL: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  JWT_SECRET_KEY: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  AWS_ACCESS_KEY_ID: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  AWS_SECRET_ACCESS_KEY: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  S3_BUCKET_NAME: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
