apiVersion: v1
kind: Service
metadata:
  name: universal-ai-gateway
  namespace: ftgo
spec:
  type: ClusterIP
  selector:
    app: universal-ai-gateway
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
