spring:
  application:
    name: ftgo-order-service

  datasource:
    url: jdbc:postgresql://postgres-order:5432/orders
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.ftgo.order.events
        spring.json.value.default.type: com.ftgo.order.events.OrderCreatedEvent
server:
  port: 8080
