apiVersion: v1
kind: Secret
metadata:
  name: restaurant-service-secret
  labels:
    app: restaurant-service
    component: backend
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "restaurant_password"
