apiVersion: v1
kind: Secret
metadata:
  name: restaurant-service-secret
  labels:
    app: restaurant-service
    component: backend
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cmVzdGF1cmFudF9wYXNzd29yZA==
