apiVersion: v1
kind: Secret
metadata:
  name: ftgo-restaurant-service-secret
  labels:
    app: restaurant-service
    component: backend
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
