apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
    component: backend
spec:
  type: ClusterIP
  selector:
    app: restaurant-service
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
