apiVersion: v1
kind: Secret
metadata:
  name: kitchen-service-secret
  labels:
    app: kitchen-service
    component: backend
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: a2l0Y2hlbl9wYXNzd29yZA==
