name: Order History Service CI

on:
  push:
    branches:
      - main
      - dev
      - feat/order-history

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ftgo-order-history-service

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: order-history-service-jar
          path: ftgo-order-history-service/target/*.jar